import Link from "next/link";

export const metadata = {
  title: "Terms of Service — peachblue",
  description: "Terms of Service for peachblue — the creative intelligence platform.",
};

export default function TermsPage() {
  return (
    <div className="max-w-[720px] mx-auto px-6 py-20">
      <Link href="/" className="text-[13px] text-pb-fg-muted hover:text-pb-fg transition-colors mb-8 inline-block">&larr; Back to home</Link>
      <h1 className="font-display text-[clamp(28px,4vw,36px)] font-medium tracking-tight mb-2">Terms of Service</h1>
      <p className="text-[13.5px] text-pb-fg-muted mb-10">Effective date: March 13, 2026 · Peachblue Technologies Inc.</p>

      <div className="prose-pb">
        <p>These Terms of Service ("Terms") govern your access to and use of the peachblue platform and related services (the "Service") provided by Peachblue Technologies Inc. ("peachblue," "we," "us," or "our"). By accessing or using the Service, you agree to be bound by these Terms.</p>

        <h2>1. Service Description</h2>
        <p>peachblue is a creative intelligence and ad performance platform that:</p>
        <ul>
          <li>Connects to advertising platforms via secure, OAuth-based API integrations</li>
          <li>Syncs creative assets (images, videos, carousels) and performance data (spend, impressions, clicks, CTR, CPC, CPM, ROAS, CPA, conversions) from your ad accounts</li>
          <li>Provides AI-powered creative analysis, generating structured intelligence tags and actionable insights about your ad creatives</li>
          <li>Offers a Creative Library for filtering, sorting, and exploring creatives by performance and intelligence tags</li>
          <li>Includes an AI assistant for natural language queries about creative performance</li>
        </ul>
        <p>The Service currently integrates with Meta Ads and TikTok Ads, with Amazon Ads and Google Ads integrations coming soon.</p>

        <h2>2. Account Registration</h2>
        <p>To use the Service, you must create an account and provide accurate, complete information. You are responsible for:</p>
        <ul>
          <li>Maintaining the security of your account credentials</li>
          <li>All activity that occurs under your account</li>
          <li>Ensuring you have proper authorization to connect any ad accounts to the Service</li>
          <li>Notifying us promptly if you suspect unauthorized access to your account</li>
        </ul>

        <h2>3. Advertising Platform Data</h2>
        <p>By connecting your advertising accounts to peachblue, you represent and warrant that:</p>
        <ul>
          <li>You have the authority and necessary permissions to grant peachblue access to the advertising data in those accounts</li>
          <li>Your use of peachblue complies with the terms of service of each connected advertising platform, including Meta Platform Terms, Google Ads API Terms of Service, Amazon Ads API License Agreement, and TikTok for Business Commercial Terms</li>
          <li>You will not use the Service to violate any advertising platform's policies or applicable laws</li>
        </ul>
        <p>peachblue accesses your advertising data solely as authorized by you and acts as a data processor on your behalf. We use your data only to provide the Service as described in our <Link href="/privacy" className="underline">Privacy Policy</Link>.</p>

        <h2>4. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Reverse engineer, decompile, or disassemble any part of the Service</li>
          <li>Scrape, crawl, or use automated means to access the Service beyond the intended interface</li>
          <li>Share your account credentials with unauthorized third parties</li>
          <li>Use the Service for any unlawful purpose or in violation of any applicable laws or regulations</li>
          <li>Attempt to gain unauthorized access to the Service, other accounts, or related systems</li>
          <li>Interfere with or disrupt the integrity or performance of the Service</li>
        </ul>

        <h2>5. Intellectual Property</h2>
        <ul>
          <li><strong>Our platform.</strong> peachblue and its underlying technology, design, and features are the intellectual property of Peachblue Technologies Inc. All rights are reserved.</li>
          <li><strong>Your data.</strong> You retain all ownership rights to your advertising data, creative assets, and account information. We claim no ownership over your data.</li>
          <li><strong>AI-generated insights.</strong> Analysis, tags, and insights generated by the Service from your data are provided to you for your use in managing your advertising performance.</li>
        </ul>

        <h2>6. Service Availability &amp; Disclaimers</h2>
        <p>The Service is currently in early access (closed alpha). As such:</p>
        <ul>
          <li>The Service is provided <strong>"as is"</strong> and <strong>"as available"</strong> without warranties of any kind, whether express or implied</li>
          <li>We do not guarantee uninterrupted or error-free operation</li>
          <li>AI-generated analysis and insights are provided for informational purposes and should not be the sole basis for business decisions</li>
          <li>Features, integrations, and functionality may change as the platform evolves</li>
          <li>We make no guarantees regarding the accuracy of AI-generated tags, scores, or recommendations</li>
        </ul>

        <h2>7. Limitation of Liability</h2>
        <p>To the maximum extent permitted by applicable law, Peachblue Technologies Inc. shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or business opportunities, arising from your use of the Service.</p>
        <p>Our total liability for any claim arising from or related to the Service shall not exceed the total fees paid by you to peachblue in the twelve (12) months preceding the claim.</p>

        <h2>8. Indemnification</h2>
        <p>You agree to indemnify and hold harmless Peachblue Technologies Inc. and its officers, directors, employees, and agents from any claims, damages, losses, or expenses (including reasonable legal fees) arising from your use of the Service or violation of these Terms.</p>

        <h2>9. Termination</h2>
        <p>Either party may terminate the Service relationship at any time. You may close your account by contacting us at <a href="mailto:nick@peachblue.io" className="underline">nick@peachblue.io</a>. We may suspend or terminate your access if you violate these Terms or for any other reason with reasonable notice.</p>
        <p>Upon termination, your right to use the Service ceases immediately. We will delete your data within 30 days of account closure, in accordance with our <Link href="/privacy" className="underline">Privacy Policy</Link>.</p>

        <h2>10. Governing Law</h2>
        <p>These Terms are governed by and construed in accordance with the laws of the Province of Ontario and the federal laws of Canada applicable therein, without regard to conflict of law principles. Any disputes arising from these Terms shall be resolved in the courts of Ontario, Canada.</p>

        <h2>11. Changes to These Terms</h2>
        <p>We may update these Terms from time to time. We will notify you of material changes by posting the updated Terms on our website and updating the effective date. Continued use of the Service after changes constitutes acceptance of the updated Terms.</p>

        <h2>12. Contact Us</h2>
        <p>If you have questions about these Terms of Service, please contact us:</p>
        <p><strong>Peachblue Technologies Inc.</strong><br /><a href="mailto:nick@peachblue.io" className="underline">nick@peachblue.io</a></p>
      </div>
    </div>
  );
}
